title: Domingos de Eul√°ria Dumba
description: Data Scientist
url: "https://www.domingosdeeulariadumba.com"
baseurl: ""

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - TODO.md
  - .gitignore
  - .github

include:
  - scripts/
  - styles/